// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuiI_GxWGQTwycMWix_z7AoKco438rfhw',
    appId: '1:1091870565064:web:3974ab751c7fbc8f3efbfd',
    messagingSenderId: '1091870565064',
    projectId: 'authentication-e9d9e',
    authDomain: 'authentication-e9d9e.firebaseapp.com',
    storageBucket: 'authentication-e9d9e.appspot.com',
    measurementId: 'G-0M1N3YZP76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCAWp7yNauBbAGSyFeLXHTDlwfE4d0TyE',
    appId: '1:1091870565064:android:eb1bd16c2e69e4b33efbfd',
    messagingSenderId: '1091870565064',
    projectId: 'authentication-e9d9e',
    storageBucket: 'authentication-e9d9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChMFN8ypCuFQ14rn0uGtsD2kzrFm7CSzI',
    appId: '1:1091870565064:ios:919f0f86516456a93efbfd',
    messagingSenderId: '1091870565064',
    projectId: 'authentication-e9d9e',
    storageBucket: 'authentication-e9d9e.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChMFN8ypCuFQ14rn0uGtsD2kzrFm7CSzI',
    appId: '1:1091870565064:ios:919f0f86516456a93efbfd',
    messagingSenderId: '1091870565064',
    projectId: 'authentication-e9d9e',
    storageBucket: 'authentication-e9d9e.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuiI_GxWGQTwycMWix_z7AoKco438rfhw',
    appId: '1:1091870565064:web:1734b1a24180a3653efbfd',
    messagingSenderId: '1091870565064',
    projectId: 'authentication-e9d9e',
    authDomain: 'authentication-e9d9e.firebaseapp.com',
    storageBucket: 'authentication-e9d9e.appspot.com',
    measurementId: 'G-PGJG8EQMDE',
  );
}
